### ISSUE TITLE
review comments

### ISSUE THREAD

**Issue by pwoznica** [nyggus/perftest#4]
# General comments

## Exceptions:
Python has an abundance of builtin exceptions (https://docs.python.org/3/library/exceptions.html) which cover most of the cases and are well understood by programmers.

Adding your own exceptions has two main drawbacks:
1. More code to maintain
2. They will be useful to you, but not necessarily to other coders (or yourself, a year from now)

## Usage
Not sure configuring the tests per function is of any use. If I need to setup the repeat count for each tested function separately, I prefer to provide this number directly to the benchmark/time_test functions instead of dealing with the `config` object. In 99% of the cases I will define a test, execute it _once_ and go to the next one.

Setting up test limits seems overcomplicated. I need to use a specific namedtuple, but it is used only for those limits, so why not provide them as regular parameters (which also simplifies the logic of choosing what is reported) and internalize this namedtuple business completely? Related: the *_test functions mix responsibilities:
1. complicated way to enter two optional arguments
2. function behaviour changes based on the arguments being there or not
3. this also governs the return type
For me this _screams_ "separate functions for tests (with limits) versus measurements"

## Config
Looks overengineered to me. Class is called Config but is so much more:
- it handles setting up the test environment (even modifying tracebacks)
- It does type checking of stored configuration
- it handles parts of the testing logic (benchmark references, reloading, etc. - this part brings tight coupling with code outside the class)
At the same time we get https://github.com/nyggus/perftest/blob/60d26aad65091fd573ee172c9c37250eb4332cd2/perftest/perftest.py#L801
which is a regular function but definitely feels like part of the class.

**Comment by pwoznica** [comment]
https://github.com/nyggus/perftest/blob/60d26aad65091fd573ee172c9c37250eb4332cd2/perftest/perftest.py#L51

Exceptions should be named after the reason for the error. Here the naming is based on which part of your code the exception is raised from.

**Comment by pwoznica** [comment]
https://github.com/nyggus/perftest/blob/60d26aad65091fd573ee172c9c37250eb4332cd2/perftest/perftest.py#L51

This is already supported in more detail by builtin exceptions:
`FileNotFoundError` (when a desired path does not exist)
`NotADirectoryError` (when a path exists but is a regular file and we wanted a directory instead)

**Comment by pwoznica** [comment]
https://github.com/nyggus/perftest/blob/60d26aad65091fd573ee172c9c37250eb4332cd2/perftest/perftest.py#L63

Better supported by builtins, since we can express more about _why_ the argument is incorrect:
`TypeError` when the type of the argument is wrong (also, python has some type-checking capability if ensuring type match in arguments)
`ValueError` when the type is correct but the value is invalid (eg. we are working with time durations and we got a negative number)

In many cases it is more useful to raise such exceptions directly where they cause problems (in some cases you can leave it to the interpreter to raise the correct ones (eg. trying to index using a float)

**Comment by pwoznica** [comment]
https://github.com/nyggus/perftest/blob/60d26aad65091fd573ee172c9c37250eb4332cd2/perftest/perftest.py#L75

Masks builtin exception of the same name. The semantics of the builtin are completely different. This _will_ confuse people.

**Comment by pwoznica** [comment]
https://github.com/nyggus/perftest/blob/60d26aad65091fd573ee172c9c37250eb4332cd2/perftest/perftest.py#L565

No need to check this. You already do it here:
https://github.com/nyggus/perftest/blob/60d26aad65091fd573ee172c9c37250eb4332cd2/perftest/perftest.py#L802

**Comment by nyggus** [comment]
> https://github.com/nyggus/perftest/blob/60d26aad65091fd573ee172c9c37250eb4332cd2/perftest/perftest.py#L51
> 
> Exceptions should be named after the reason for the error. Here the naming is based on which part of your code the exception is raised from.

I am not sure I know what you mean. I do agree that exception names need revision, but they do represent the reason for the error. Like here, `CLIPathError` (along with the message) informs that the user provided an incorrect path in a command-line interface. `PathError`, on the other hand, is used in different scenarios - when a user provided an incorrect path inside his or her `perftest` code.

**Comment by nyggus** [comment]
> https://github.com/nyggus/perftest/blob/60d26aad65091fd573ee172c9c37250eb4332cd2/perftest/perftest.py#L565
> 
> No need to check this. You already do it here:
> 
> https://github.com/nyggus/perftest/blob/60d26aad65091fd573ee172c9c37250eb4332cd2/perftest/perftest.py#L802

Yes, definitely true.

**Comment by nyggus** [comment]
> https://github.com/nyggus/perftest/blob/60d26aad65091fd573ee172c9c37250eb4332cd2/perftest/perftest.py#L75
> 
> Masks builtin exception of the same name. The semantics of the builtin are completely different. This _will_ confuse people.

Definitely true. Besides, I was thinking of changing test-related names to `MemoryTestError` and `TimeTestError` so that they are clearer.

**Comment by nyggus** [comment]
> https://github.com/nyggus/perftest/blob/60d26aad65091fd573ee172c9c37250eb4332cd2/perftest/perftest.py#L57
> 
> This is already supported in more detail by builtin exceptions: `FileNotFoundError` (when a desired path does not exist) `NotADirectoryError` (when a path exists but is a regular file and we wanted a directory instead)

`PathError` is used for a log file, so the name is not sufficient (maybe I will change it to `IncorrectPathToLogFileError`, a very clear name), but I prefer to use a custom exception instead of built-in ones. There are two schools: use built-in exception classes whenever you can, and build custom exception classes. For a project like this, I definitely prefer custom exceptions, so that the user immediately knows that the exception was raises directly in `perftest`, what was the reason of this exception, and how to improve it. With built-in ones, the user will often have to analyze the traceback to learn this. And note that with `perftest`, traceback is on default shortened, so we should provide as much information as possible in the exception itself.

**Comment by nyggus** [comment]
> Setting up test limits seems overcomplicated. I need to use a specific namedtuple, but it is used only for those limits, so why not provide them as regular parameters (which also simplifies the logic of choosing what is reported) and internalize this namedtuple business completely?

That's true. I was hesitating whether to use a tuple or not. In fact, you can provide a regular tuple, but maybe you're right that it's easier to use two arguments instead, like `raw_limit` and `relative_limit`.

**Comment by nyggus** [comment]
> Not sure configuring the tests per function is of any use. If I need to setup the repeat count for each tested function separately, I prefer to provide this number directly to the benchmark/time_test functions instead of dealing with the config object. In 99% of the cases I will define a test, execute it once and go to the next one.

I know `config` complicates things, but I decided to design it that way for one reason: to simplify using the testing functions. Note that when you're passing a `number` argument to `time_test`, you can have problems when you have a tested function that takes an argument of `number` (or `repeat`), since you will have two arguments of the same name. In addition, remember that `time_test` and `memory_usage_test` take `*args` and `kwargs`, so if you want them to take additional default arguments (`number` and `repeat`), you will have to make them keywords-only (but this does not solve the problem of overwriting the `number` and `repeat` arguments).

That's why I decided to pass all configuration to the `config` object - but if you have a better idea how to solve these issues, I will be happy to implement them.

**Comment by nyggus** [comment]
> Python has an abundance of builtin exceptions (https://docs.python.org/3/library/exceptions.html) which cover most of the cases and are well understood by programmers.

> Adding your own exceptions has two main drawbacks:

> * More code to maintain
> * They will be useful to you, but not necessarily to other coders (or yourself, a year from now)

I commented on that elsewhere, but I'd like to add here that both schools have their believers. Some time ago I was somewhere in between, but Dan Bader convinced me in his [Python tricks](https://realpython.com/products/python-tricks-book/) book, where he convinces why custom exceptions can be of great help.

**Comment by nyggus** [comment]
> In 99% of the cases I will define a test, execute it once and go to the next one.

In most cases (maybe not 99%, but still a lot) you can use default values, so no need to do anything with the settings collected in the `config`. (But again, if you have a good idea how to simplify things, I will be happy to implement that.)

**Comment by nyggus** [comment]
> For me this screams "separate functions for tests (with limits) versus measurements"

This can be done. But if you think about that: if you do not provide limits, then you simply get benchmarks. In my eyes, this is actually making things simpler than more difficult. Otherwise, you will have to complicate something else. For instance, you can revise the `benchmark` function, by adding an argument to pass information which benchmarks (time, memory, both) you want to make. Or you can add two functions for time benchmarks and memory benchmarks. I think any of these solutions will make things more complicated.

As mentioned above, the current flow is as follows: You provide limits, you have your test. You do not, you see the results. That's it - is it making using `perftest` indeed that complex?

**Comment by nyggus** [comment]
All comments has been implemented in the new version of the package.
